#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2022, Konrad Weihmann

import json
import os
import re

DATA_FILE = os.path.join(os.path.dirname(
    __file__), '..', 'osadl_matrix', 'osadl-matrix.json')


def escape_name(inp: str) -> str:
    return re.sub(r'[\s\.-]', '_', inp)


def map_result(inp: str) -> str:
    map_ = {'Check dependency': 'CHECKDEP', 'Same': 'YES',
            'Yes': 'YES', 'No': 'NO', 'Unknown': 'UNKNOWN'}
    return map_.get(inp, 'UNDEF')


def gen_test_case(a: str, b: str, expected: str) -> str:
    res = f'''
    def test_{escape_name(a)}_{escape_name(b)}(self):        
        assert osadl_matrix.get_compatibility("{a}", "{b}") == osadl_matrix.OSADLCompatibility.{map_result(expected)}
    '''
    return res


print('# SPDX-FileCopyrightText: 2022 Konrad Weihmann')
print('# SPDX-License-Identifier: Unlicensed')
print('')
print('import pytest')
print('import osadl_matrix')
print('')
print('class TestSnapshot():')

with open(DATA_FILE) as i:
    for a, v in json.load(i).items():
        if not isinstance(v, dict):
            continue
        for b, comp in v.items():
            print(gen_test_case(a, b, comp))
