name: 'Cron bump'

on:
  repository_dispatch:
    types: do-cron
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    name: 'scrap and push'

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: scrap
      run: |
        pip3 install -r requirements-dev.txt
        python3 scripts/scrapper.py
      shell: bash
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: build
      run: python3 setup.py build
      shell: bash
    - name: install more dependencies
      run: |
        pip install -r requirements-dev.txt
      shell: bash
    - name: test
      run: |
        pytest
      shell: bash
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Bump matrix'
        files: osadl_matrix/osadl-matrix.csv osadl_matrix/osadl-matrix.json
        name: ${{ secrets.COMMITER_NAME }}
        email: ${{ secrets.COMMITER_MAIL }}
        rebase: 'true'
