name: 'push and release master'

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types: cron_release

jobs:
  build:
    name: 'push and release'

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - uses: dorny/paths-filter@v3.0.2
      id: code-changes
      with:
        filters: |
          code_changes:
            - 'osadl_matrix/**/*'
            - 'osadl_matrix/*'
            - 'LICENSE*'
            - 'README.md'
            - 'requirements.txt'
            - 'MANIFEST.in'
            - 'setup.py'
            - 'VERSION'
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
      shell: bash
    - name: lint
      run: |
        flake8
    - name: build
      run: python3 setup.py build
      shell: bash
    - name: test
      run: |
        pytest
      shell: bash
    - name: bump version
      if: steps.code-changes.outputs.code_changes == 'true' || github.event_name == 'workflow_dispatch'
      run: |
        date --utc '+%Y.%m.%d.%H%m%S' | tr -d '\n' > VERSION
      shell: bash
    - name: push
      if: steps.code-changes.outputs.code_changes == 'true' || github.event_name == 'workflow_dispatch'
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Bump version'
        files: VERSION
        name: ${{ secrets.COMMITER_NAME }}
        email: ${{ secrets.COMMITER_MAIL }}
        rebase: 'true'
    - name: tag version
      if: steps.code-changes.outputs.code_changes == 'true' || github.event_name == 'workflow_dispatch'
      uses: butlerlogic/action-autotag@1.1.2
      with:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        strategy: regex
        root: "VERSION"
        regex_pattern: '(.*)'
    - name: create sdist release
      if: steps.code-changes.outputs.code_changes == 'true' || github.event_name == 'workflow_dispatch'
      run: python3 setup.py sdist
      shell: bash        
    - name: publish package
      if: steps.code-changes.outputs.code_changes == 'true' || github.event_name == 'workflow_dispatch'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
