name: 'manual release'

on:
  workflow_dispatch:

jobs:
  build:
    name: 'prelease'

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
      shell: bash
    - name: lint
      run: |
        flake8
    - name: build
      run: python3 setup.py build
      shell: bash
    - name: test
      run: |
        pytest
      shell: bash
    - name: bump version
      run: |
        date --utc '+%Y.%m.%d.%H%m%S' | tr -d '\n' > VERSION
      shell: bash
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Bump version'
        files: VERSION
        name: ${{ secrets.COMMITER_NAME }}
        email: ${{ secrets.COMMITER_MAIL }}
        rebase: 'true'
    - name: tag version
      uses: butlerlogic/action-autotag@1.1.4
      with:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        strategy: regex
        root: "VERSION"
        regex_pattern: '(.*)'
    - name: create sdist release
      run: python3 setup.py sdist
      shell: bash        
    - name: publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
